name: flutter_sunflower
description: A Flutter version of Sunflower.

environment:
  sdk: '>=3.7.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sc.png
    